### PR TITLE
change compile target to ES5, because IE11 does not support ES classes

### PR DESCRIPTION
**Pull request by gfx**
Thanks to the awesome library, but I have issues on production when users use IE11.

`target: "es6"` is too early, I guess.

### CODE REVIEW

**Comment by dan-lee** [comment]
Any chance this can be merged and released? This library does not compile with `create-react-app` because of [`npm run build` fails to minify](https://github.com/facebook/create-react-app/blob/86a82b1626927133b9f8bcd2270c8582bb32f2f9/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

**Comment by gfx** [comment]
@davetemplin ping

**Comment by PS-davetemplin** [comment]
Hey thanks for the PR! Considering it--what are the build errors you're seeing?

**Comment by dan-lee** [comment]
For me it was something like:

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file: 
> 
>  	./path/to/async-parallel
> 
> Read more here: http://bit.ly/2tRViJ9

**Comment by davetemplin** [comment]
After careful consideration, I think it's actually best for this library to move ahead to a new major version targeting `esnext` which is going the wrong direction for your case. :-) Have you considered introducing babel (or something like that) into your build pipeline? Another option is we could put out a different version of this component that targets downlevel to es5. Let me know what you think.

**Comment by gfx** [comment]
@davetemplin Thanks to the consideration. Because we do not use Babel (and won't use Babel in a future), we should find another parallel async library, unfortunately.

**Pull request closed without merging**
